FROM node:20.9.0-alpine as buildtime

WORKDIR /app

COPY client/package*.json .

RUN npm install

COPY client/ .

ARG VITE_BASE_URL
ENV VITE_BASE_URL=${VITE_BASE_URL}

RUN npm run build

EXPOSE 80

ENTRYPOINT [ "npm", "run", "preview" ]
